import { useState } from "react";

type Tab = "agenda" | "servicios" | "clientes" | "perfil";
const appointments = [
  { time: "09:00", name: "Valentina Pérez", service: "Manicura clásica", duration: "45 min", color: "pink", status: "Confirmada" },
  { time: "10:30", name: "Camila Rodríguez", service: "Uñas acrílicas", duration: "90 min", color: "sand", status: "Confirmada" },
  { time: "13:00", name: "Sofía Martínez", service: "Gel con diseño", duration: "60 min", color: "lilac", status: "Por confirmar" },
  { time: "15:00", name: "Isabella Díaz", service: "Retirada + manicura", duration: "45 min", color: "pink", status: "Confirmada" }
];
const week = [{d:"LUN",n:"06"},{d:"MAR",n:"07"},{d:"MIÉ",n:"08"},{d:"JUE",n:"09"},{d:"VIE",n:"10"},{d:"SÁB",n:"11"},{d:"DOM",n:"12"}];
const serviceList = [{name:"Manicura clásica",desc:"Cuidado y acabado natural",duration:"45 min",price:"800 CUP",symbol:"✿"},{name:"Uñas acrílicas",desc:"Extensión y forma personalizada",duration:"90 min",price:"1 800 CUP",symbol:"✧"},{name:"Gel con diseño",desc:"Color duradero y detalles",duration:"60 min",price:"1 400 CUP",symbol:"❀"}];

export default function App() {
 const [tab,setTab] = useState<Tab>("agenda");
 const [day,setDay] = useState("09");
 const [showNew,setShowNew] = useState(false);
 const [newName,setNewName] = useState("");
 const [newService,setNewService] = useState("Manicura clásica");
 const [newTime,setNewTime] = useState("16:30");
 const [extra,setExtra] = useState<{name:string;service:string;time:string}[]>([]);
 const [notice,setNotice] = useState("");
 const list = [...appointments.filter(a => day !== "09" ? false : true), ...extra.map(a => ({time:a.time,name:a.name,service:a.service,duration:"Por definir",color:"pink",status:"Pendiente local"}))].sort((a,b)=>a.time.localeCompare(b.time));

 const addAppointment = () => {
   if (!newName.trim()) { setNotice("Escribe el nombre de la clienta para continuar."); return; }
   setExtra(prev => [...prev,{name:newName.trim(),service:newService,time:newTime}].sort((a,b)=>a.time.localeCompare(b.time)));
   setShowNew(false); setNotice("Cita añadida a esta vista como pendiente local. Aún no se ha guardado en la base de datos."); setNewName("");
 };

 return <main className="provider-shell">
  <aside className="provider-sidebar"><div className="provider-brand"><div className="provider-mark">l<span>✦</span></div><div><b>luni</b><small>STUDIO</small></div></div><div className="studio-switch"><div className="studio-avatar">A</div><div><b>Mi estudio</b><small>Espacio de belleza</small></div><span>⌄</span></div><div className="side-label">ESPACIO DE TRABAJO</div><nav className="side-nav"><button className={tab==="agenda"?"selected":""} onClick={()=>setTab("agenda")}><span>▦</span> Agenda</button><button className={tab==="servicios"?"selected":""} onClick={()=>setTab("servicios")}><span>✧</span> Mis servicios</button><button className={tab==="clientes"?"selected":""} onClick={()=>setTab("clientes")}><span>♙</span> Clientas</button><button className={tab==="perfil"?"selected":""} onClick={()=>setTab("perfil")}><span>⚙</span> Mi negocio</button></nav><div className="sidebar-bottom"><div className="help-mark">♡</div><b>Un espacio para crecer</b><p>Organiza tu tiempo. Cuida cada detalle.</p><span className="trial-pill">PRUEBA GRATUITA · 14 DÍAS</span><div className="user-mini"><div className="studio-avatar">A</div><div><b>Administradora</b><small>Mi cuenta</small></div><span>···</span></div></div></aside>
  <section className="provider-main"><header className="provider-header"><div className="mobile-brand"><div className="provider-mark">l<span>✦</span></div><b>luni studio</b></div><div className="breadcrumb">Mi estudio <span>/</span> <b>{tab==="agenda"?"Agenda":tab==="servicios"?"Mis servicios":tab==="clientes"?"Clientas":"Mi negocio"}</b></div><div className="header-actions"><span className="connection-dot"></span><span className="connection-label">Vista de demostración</span><button className="header-avatar" onClick={()=>setTab("perfil")}>A</button></div></header>
   {tab==="agenda" && <div className="workspace"><div className="welcome-row"><div><span className="eyebrow">JUEVES, 9 DE OCTUBRE</span><h1>Tu día, <em>a tu manera.</em></h1><p>Un paso a la vez, una clienta a la vez.</p></div><button className="provider-primary" onClick={()=>{setShowNew(true);setNotice("");}}>＋ Nueva cita</button></div>
    <div className="metric-grid"><article className="metric-card"><span>CITAS DE HOY</span><div><b>{day==="09"?4+extra.length:0}</b><i>▦</i></div><small>En tu agenda</small></article><article className="metric-card"><span>INGRESOS PREVISTOS</span><div><b>{day==="09"?"5 400":"0"} <small>CUP</small></b><i>♧</i></div><small>Según citas de hoy</small></article><article className="metric-card"><span>POR CONFIRMAR</span><div><b>{day==="09"?1:0}</b><i>◷</i></div><small>Requieren seguimiento</small></article></div>
    <section className="agenda-panel"><div className="agenda-heading"><div><h2>Agenda</h2><p>Organiza tus citas con calma.</p></div><button className="today-button" onClick={()=>setDay("09")}>Hoy <span>⌄</span></button></div><div className="week-strip">{week.map(w=><button key={w.n} onClick={()=>setDay(w.n)} className={day===w.n?"day active-day":"day"}><span>{w.d}</span><b>{w.n}</b>{day===w.n&&<i/>}</button>)}</div><div className="agenda-date"><b>{day==="09"?"Jueves, 9 de octubre":week.find(w=>w.n===day)?.d+", "+day+" de octubre"}</b><span>{day==="09"?"4 citas programadas":"Agenda del día"}</span></div>
    <div className="appointment-list">{(day==="09"?list:[]).map((a,i)=><article className="provider-appointment" key={a.time+a.name}><div className="appointment-time"><b>{a.time}</b><span>{a.duration}</span></div><div className={"appointment-color "+a.color}></div><div className="appointment-details"><b>{a.name}</b><span>{a.service}</span></div><span className={a.status==="Confirmada"?"appointment-status confirmed":"appointment-status waiting"}>{a.status}</span><button className="more-button" aria-label={"Opciones de cita de "+a.name} onClick={()=>setNotice("Las acciones de cita se conectarán al backend en la siguiente fase.")}>···</button></article>)}{day!=="09"&&<div className="provider-empty"><span>✧</span><b>Un día para crear espacio</b><p>No hay citas en esta vista de demostración.</p><button className="provider-secondary" onClick={()=>setShowNew(true)}>Añadir cita</button></div>}</div>
    </section>{notice&&<div className="provider-notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    <div className="bottom-tip"><span>✧</span><div><b>Un pequeño recordatorio</b><p>Deja unos minutos entre citas para preparar tu espacio y disfrutar el proceso.</p></div></div>
   </div>}
   {tab==="servicios"&&<div className="workspace"><div className="welcome-row"><div><span className="eyebrow">LO QUE HACES MEJOR</span><h1>Mis <em>servicios.</em></h1><p>Cuida cada detalle de lo que ofreces.</p></div><button className="provider-primary" onClick={()=>setNotice("El formulario para crear servicios se habilitará al conectar la base de datos.")}>＋ Añadir servicio</button></div><div className="provider-service-grid">{serviceList.map((s,i)=><article className="provider-service-card" key={s.name}><div className={"provider-service-art art-"+i}>{s.symbol}<span>0{i+1}</span></div><div className="provider-service-content"><h3>{s.name}</h3><p>{s.desc}</p><div><span>◷ {s.duration}</span><b>{s.price}</b></div><button className="provider-secondary" onClick={()=>setNotice("La edición de servicios se conectará a Supabase en la siguiente fase.")}>Editar detalles ↗</button></div></article>)}</div>{notice&&<div className="provider-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>}
   {tab==="clientes"&&<div className="workspace"><span className="eyebrow">RELACIONES QUE IMPORTAN</span><h1>Tus <em>clientas.</em></h1><div className="provider-empty large-empty"><span>♡</span><b>Tu comunidad empieza aquí</b><p>Cuando conectemos la agenda, aquí encontrarás el historial y las preferencias de tus clientas.</p></div></div>}
   {tab==="perfil"&&<div className="workspace"><span className="eyebrow">TU MARCA, TUS REGLAS</span><h1>Mi <em>negocio.</em></h1><div className="settings-card"><div className="settings-avatar">A</div><div><h3>Mi estudio de belleza</h3><p>Personaliza el nombre, la información pública y tus horarios.</p></div><span className="trial-pill">PRUEBA · 14 DÍAS</span></div><div className="settings-card"><div className="settings-icon">◷</div><div><h3>Horario de atención</h3><p>Configura días laborables, pausas y excepciones.</p></div><button className="provider-secondary" onClick={()=>setNotice("La configuración de horarios se implementará con el modelo de disponibilidad.")}>Configurar</button></div>{notice&&<div className="provider-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}</div>}
   <footer className="provider-footer"><span>luni studio</span><span>Hecho con cuidado, para quienes cuidan. ♡</span></footer>
  </section>
  {showNew&&<div className="provider-modal-backdrop"><section className="provider-modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><button className="modal-close" onClick={()=>setShowNew(false)} aria-label="Cerrar">×</button><span className="eyebrow">HAZLE ESPACIO</span><h2 id="new-title">Añadir una <em>cita.</em></h2><label>Nombre de la clienta<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Ej. Ana Rodríguez"/></label><label>Servicio<select value={newService} onChange={e=>setNewService(e.target.value)}>{serviceList.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Hora preferida<input type="time" value={newTime} onChange={e=>setNewTime(e.target.value)}/></label><p>Se añadirá únicamente a esta vista de demostración. La persistencia local y la sincronización se implementarán después.</p><button className="provider-primary full-provider-button" onClick={addAppointment}>Añadir a la vista</button></section></div>}
 </main>;
}
